### ISSUE TITLE
I can see gui of margarita but can't create new branch after updating margarita.

### ISSUE THREAD

**Issue by sprintership** [jessepeterson/margarita#47] opened 2016-05-06 16:52 UTC

**Comment by sprintership** [comment] 2016-05-06 16:53
I can see only blue stripe

**Comment by cashxx** [comment] 2016-05-07 13:11
Just updated as well and having the same problem.  Have a text field to create branch name and then a blue "Create New Branch" button and that is it.  Just rebooted server and still nothing.  Ugg..

**Comment by jessepeterson** [comment] 2016-06-06 17:15
@sprintership: are you still seeing issues? if you grab a fresh copy, restart your server, and perform a sync of margarita do things start working like for @cashxx?

**Comment by sprintership** [comment] 2016-06-07 17:36
Hi, looks like ./repo_sync does the trick with branches after rebooting the server. IS there any fix to that ? Thx

**Comment by jessepeterson** [comment] 2016-07-03 00:48
I'm unable to reproduce this issue. Can you provide a set of steps to reproduce including instructions on how you've setup your environment??

**Comment by franton** [comment] 2016-09-19 13:07
Seen this before. It's usually file system ownership and permission issues.

**Comment by jessepeterson** [comment] 2018-06-26 23:18
Closing issue as there was no follow-up from OP.

**Closed by jessepeterson** 2018-06-26 23:18 UTC
